### ISSUE TITLE
Assign members that have a custom role in the project

### ISSUE THREAD

**Issue by Cyboulette** [creecros/Group_assign#24]
Hello,

I want to use this plugin on Kanboard v1.2.6 but I have a little question or asking feature.

Groups are only configurable by the platform administrator, the projects owners/manager can't create groups they can only add groups to their project. Then, if they want to assign a "group of user" this group need to be created by the platform administrator.

Do you think it's possible to assign "groups of Custom roles", because these custom roles can be created by the project manager and assigned to people. It's like a group but with custom permissions/restrictions.

If you can do this, it means it will be possible for project manager to manage their projects without intervention of project administrator :)

Thanks for your future answer.

**Comment by creecros** [comment]
Roles and groups are 2 different things, completely unrelated. What is it exactly that you want? The ability for project manager's to create groups?

**Comment by Cyboulette** [comment]
Yes. Is it possible ? I'm not sure to have found this.

Le mer. 16 janv. 2019 à 13:57, Craig Crosby <notifications@github.com> a
écrit :

**Comment by creecros** [comment]
Anythings possible. Only place to find such a thing, would be in your mind, until you make it happen. I'll make it happen for you. Just not sure when I'll get to it, maybe later today, maybe later this week, month, year...probably sooner than later.

**Comment by Cyboulette** [comment]
I see :) Thanks a lot, In another plugin I think ?

**Comment by creecros** [comment]
no, I took care of it. Can't do it for Project Managers though, that would require quite a bit of work, and the current Kanboard system would not allow it, since groups are application wide. Just take my word for it, that would be an entirely seperate plugin that I don't want to create, tbh.

I did however add the ability for Application Managers to manage groups for you. You can turn the settings on in `Settings > Application settings`
![image](https://user-images.githubusercontent.com/26339368/51257433-97ca5b00-1975-11e9-89dc-db32ab30dafa.png)

And App Managers will have the ability to manage groups.

**Comment by Cyboulette** [comment]
Perfect, you're the best :)

All my Project Managers are already Application Managers.

Thanks a lot.

**Comment by creecros** [comment]
Oh, it's version 1.6.0, you'll have to manually install, or wait till the merge on the website before you can install in the plugin interface.

https://github.com/creecros/Group_assign/releases/tag/1.6.0

**Comment by creecros** [comment]
also, ⭐️ my repo. it makes me happy to see stars...
