### ISSUE TITLE
Task assigned to a group visible on all group member's calendar view

### ISSUE THREAD

**Issue by mapeze** [creecros/Group_assign#4]
When calendar plugin is installed and a task is assigned to a group, the task should be visible on all group member's calendar view.

**Comment by creecros** [comment]
The calendar plugin? Not the built in calendar?  Can you link the plugin?

**Comment by creecros** [comment]
Any idea what the difference is between the calendar plug in and the built in plugin? I might be able to do something about the built in calendar, but I can't do anything about the plugin, aside from making a new plugin or including the functionlaity of the plugin into this plugin, but it wouldn't work with an existing plugin that somoney else maintains, they would have to incorporate, which would probably make this plugin a requirement for their plugin. All that aside, I still need to actually look at the code and figure out what needs to be done, guessing it's in the ICalenderController.php

**Comment by mapeze** [comment]
Kanboard 1.2.4 does not seem to have a built-in calendar... (or just I did not found the way to activate it).
We installed
https://github.com/kanboard/plugin-calendar
If Kanboard has a built-in calendar module, we should then check how group-assign plugin works there.

My php knowledge is very very limited. In mysql I could be of more help. A comment if it helps:

In the group-assign plugin page I see "...using assignee:'Username' or assignee:'Name' will NOT find a task assigned to a group with that UserName or Name", and this is later referred as future enhancement. Supposing this is done, then maybe it would be enough to override the default filter the calendar plugin uses "assignee:me" with "assignee:Username". Forget it if I´m just confusing you.

**Comment by creecros** [comment]
No, that wouldn't make it work, that just adds the relation in the search field. I'm going to look into it, just, very busy with real life job at the moment.

**Comment by creecros** [comment]
Just realized I had the calendar plugin installed, didn't even realize.

**Comment by creecros** [comment]
figured it out, but it would have to be done at the Calendar Plugin Level, because it directly calls `Kanboard\Filter\TaskAssigneeFilter` in the CalendarController, so it will never utilize the one provided in my Plugin.

I forked it for you, and edited the code here: https://github.com/creecros/plugin-calendar

![image](https://user-images.githubusercontent.com/26339368/41307518-6c3e976e-6e47-11e8-8f71-cef11142a3da.png)

**Comment by mapeze** [comment]
Thank you very much!!!

I made it work editing the original TaskAssigneeFilter.php at line 63 to 66 according to your CalendarPlugin's TaskAssigneeFilter.php.

However installing your CalendarPlugin still does not show the task assigned to a group (tasks assigned to me are shown).

**Comment by creecros** [comment]
I might have some typos, I'll take a look later.

On Jun 12, 2018 6:20 PM, "mapeze" <notifications@github.com> wrote:

Thank you very much!!!

I made it work editing the original TaskAssigneeFilter.php at line 63 to 66
according to your CalendarPlugin's TaskAssigneeFilter.php.

However installing your CalendarPlugin still does not show the task
assigned to a group (tasks assigned to me are shown).

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/creecros/Group_assign/issues/4#issuecomment-396753030>,
or mute the thread

**Comment by creecros** [comment]
Yup, i'm accident prone:
![image](https://user-images.githubusercontent.com/26339368/41322170-8f8005e0-6e75-11e8-8d88-4f132f798aa8.png)

All fixed.

**Comment by creecros** [comment]
@mapeze 

I added the events to the calendar via merge hooks, no need to use the forked calendar plugin anymore.
