### ISSUE TITLE
Make this plugin work with the search

### ISSUE THREAD

**Issue by hugosxm** [creecros/Group_assign#63]
Hi,

thanks for this plugin that we use A LOT ! We just found a little flaw => if you create a task, you assign user A, then other assignee you put user B. When using the search with status:open assignee:me, you won't find the card if you are in the search result. I think the fix is easy because it works on the dashboard "My tasks"

**Comment by creecros** [comment]
are you user A or B in this scenario

**Comment by hugosxm** [comment]
I'm A in that scenario, I can provide full screenshot procedure if my text is not clear :)

**Comment by creecros** [comment]
ya maybe add a screenshot, and confirm your version, both KB and the plugin version.

**Comment by creecros** [comment]
in the screenshots. show me an example task as well as result.

**Comment by creecros** [comment]
but either way....assignee:me is not a filter in group assign...so test that without the plugin, not sure what I can even do on that. that might be a flaw in kanboard.

**Comment by auge8472** [comment]
Just to clarify the issue a bit. A ticket is assigned to user A. Based on this plugin the user B gets assigned with the input field "Other assignees".

On the dashboard of user B the assignment is visible in user B's tasks. Also the pin board shows the line "Other assignees" in the card of the task. But wether the filter "assignee: me" (for user B) in the dashboard nor the filter "assignee: B" in the projects own filter function shows the tasks where B is (one of) the "Other assignee(s)".

**Comment by creecros** [comment]
I think I stated this already, but just to be clear, "assignee:" is not a filter of group assign. nor will "assignee:" find any task assigned to you or anyone else if assigneed as other assignee. you have to use "allassignees:", which is a filter in group assign.

**Comment by auge8472** [comment]
> you have to use "", which is a filter in group assign.

With initial use of group filter (`allassignees:`) I can only select a groups name that is connected with the project. When I afterwards replace the group name with the name of user B in the input field, I get the wanted result. So far, so good. Thank you, that helps me a lot.

Is there a way to add the members (users) of a project to the select list of the filter button for groups? That would be much of help because one wouldn't need either to type in the complete filter string or to perform a first search to correct the search term after an ainitial search/filter run. Is there maybe an existing plugin?

**BTW**: I think, you didn't state that clear enough (at least for me, in this issue). You wrote *"assignee:me is not a filter in group assign"* but nothing about the use of `allassignees:` *to input a specific user name*, so it was not clear for me, that this would be the way to go. Anyway, now I know it.

**Comment by creecros** [comment]
no worries, I did not state it in this thread, but I do make it clear in the Readme.

**Comment by creecros** [comment]
I think the Readme clears this up and is a non issue.
